//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ui : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractMain
        {
            get
            {
                return SteamVR_Actions.ui_InteractMain;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractMiddle
        {
            get
            {
                return SteamVR_Actions.ui_InteractMiddle;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractContext
        {
            get
            {
                return SteamVR_Actions.ui_InteractContext;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickScroll
        {
            get
            {
                return SteamVR_Actions.ui_JoystickScroll;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadScrollTouch
        {
            get
            {
                return SteamVR_Actions.ui_TouchpadScrollTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadScrollPosition
        {
            get
            {
                return SteamVR_Actions.ui_TouchpadScrollPosition;
            }
        }
        
        public virtual SteamVR_Action_Pose UIPointer
        {
            get
            {
                return SteamVR_Actions.ui_UIPointer;
            }
        }
    }
}
