//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_ui_InteractMain;
        
        private static SteamVR_Action_Boolean p_ui_InteractMiddle;
        
        private static SteamVR_Action_Boolean p_ui_InteractContext;
        
        private static SteamVR_Action_Vector2 p_ui_JoystickScroll;
        
        private static SteamVR_Action_Boolean p_ui_TouchpadScrollTouch;
        
        private static SteamVR_Action_Vector2 p_ui_TouchpadScrollPosition;
        
        private static SteamVR_Action_Pose p_ui_UIPointer;
        
        public static SteamVR_Action_Boolean ui_InteractMain
        {
            get
            {
                return SteamVR_Actions.p_ui_InteractMain.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean ui_InteractMiddle
        {
            get
            {
                return SteamVR_Actions.p_ui_InteractMiddle.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean ui_InteractContext
        {
            get
            {
                return SteamVR_Actions.p_ui_InteractContext.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 ui_JoystickScroll
        {
            get
            {
                return SteamVR_Actions.p_ui_JoystickScroll.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean ui_TouchpadScrollTouch
        {
            get
            {
                return SteamVR_Actions.p_ui_TouchpadScrollTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 ui_TouchpadScrollPosition
        {
            get
            {
                return SteamVR_Actions.p_ui_TouchpadScrollPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose ui_UIPointer
        {
            get
            {
                return SteamVR_Actions.p_ui_UIPointer.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.ui_InteractMain,
                    SteamVR_Actions.ui_InteractMiddle,
                    SteamVR_Actions.ui_InteractContext,
                    SteamVR_Actions.ui_JoystickScroll,
                    SteamVR_Actions.ui_TouchpadScrollTouch,
                    SteamVR_Actions.ui_TouchpadScrollPosition,
                    SteamVR_Actions.ui_UIPointer};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.ui_InteractMain,
                    SteamVR_Actions.ui_InteractMiddle,
                    SteamVR_Actions.ui_InteractContext,
                    SteamVR_Actions.ui_JoystickScroll,
                    SteamVR_Actions.ui_TouchpadScrollTouch,
                    SteamVR_Actions.ui_TouchpadScrollPosition,
                    SteamVR_Actions.ui_UIPointer};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.ui_UIPointer};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.ui_InteractMain,
                    SteamVR_Actions.ui_InteractMiddle,
                    SteamVR_Actions.ui_InteractContext,
                    SteamVR_Actions.ui_TouchpadScrollTouch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.ui_JoystickScroll,
                    SteamVR_Actions.ui_TouchpadScrollPosition};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.ui_InteractMain,
                    SteamVR_Actions.ui_InteractMiddle,
                    SteamVR_Actions.ui_InteractContext,
                    SteamVR_Actions.ui_JoystickScroll,
                    SteamVR_Actions.ui_TouchpadScrollTouch,
                    SteamVR_Actions.ui_TouchpadScrollPosition};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_ui_InteractMain = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/ui/in/InteractMain")));
            SteamVR_Actions.p_ui_InteractMiddle = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/ui/in/InteractMiddle")));
            SteamVR_Actions.p_ui_InteractContext = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/ui/in/InteractContext")));
            SteamVR_Actions.p_ui_JoystickScroll = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/ui/in/JoystickScroll")));
            SteamVR_Actions.p_ui_TouchpadScrollTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/ui/in/TouchpadScrollTouch")));
            SteamVR_Actions.p_ui_TouchpadScrollPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/ui/in/TouchpadScrollPosition")));
            SteamVR_Actions.p_ui_UIPointer = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/ui/in/UIPointer")));
        }
    }
}
